package com.sia.model;
// Generated Apr 8, 2013 1:51:16 PM by Hibernate Tools 3.2.1.GA



/**
 * AbsenId generated by hbm2java
 */
public class AbsenId  implements java.io.Serializable {


     private int kodeMk;
     private int kodeRuang;
     private int nim;

    public AbsenId() {
    }

    public AbsenId(int kodeMk, int kodeRuang, int nim) {
       this.kodeMk = kodeMk;
       this.kodeRuang = kodeRuang;
       this.nim = nim;
    }
   
    public int getKodeMk() {
        return this.kodeMk;
    }
    
    public void setKodeMk(int kodeMk) {
        this.kodeMk = kodeMk;
    }
    public int getKodeRuang() {
        return this.kodeRuang;
    }
    
    public void setKodeRuang(int kodeRuang) {
        this.kodeRuang = kodeRuang;
    }
    public int getNim() {
        return this.nim;
    }
    
    public void setNim(int nim) {
        this.nim = nim;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AbsenId) ) return false;
		 AbsenId castOther = ( AbsenId ) other; 
         
		 return (this.getKodeMk()==castOther.getKodeMk())
 && (this.getKodeRuang()==castOther.getKodeRuang())
 && (this.getNim()==castOther.getNim());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getKodeMk();
         result = 37 * result + this.getKodeRuang();
         result = 37 * result + this.getNim();
         return result;
   }   


}


