package com.sia.model;
// Generated Apr 8, 2013 1:51:16 PM by Hibernate Tools 3.2.1.GA



/**
 * Absen generated by hbm2java
 */
public class Absen  implements java.io.Serializable {


     private AbsenId id;
     private Ruang ruang;
     private Mahasiswa mahasiswa;
     private Matakuliah matakuliah;
     private int jam;
     private int hari;
     private Integer absen1;
     private Integer absen2;
     private Integer absen3;
     private Integer absen4;
     private Integer absen5;
     private Integer absen6;
     private Integer absen7;
     private Integer absen8;
     private Integer absen9;
     private Integer absen10;
     private Integer absen11;
     private Integer absen12;
     private Integer absen13;
     private Integer absen14;

    public Absen() {
    }

	
    public Absen(AbsenId id, Ruang ruang, Mahasiswa mahasiswa, Matakuliah matakuliah, int jam, int hari) {
        this.id = id;
        this.ruang = ruang;
        this.mahasiswa = mahasiswa;
        this.matakuliah = matakuliah;
        this.jam = jam;
        this.hari = hari;
    }
    public Absen(AbsenId id, Ruang ruang, Mahasiswa mahasiswa, Matakuliah matakuliah, int jam, int hari, Integer absen1, Integer absen2, Integer absen3, Integer absen4, Integer absen5, Integer absen6, Integer absen7, Integer absen8, Integer absen9, Integer absen10, Integer absen11, Integer absen12, Integer absen13, Integer absen14) {
       this.id = id;
       this.ruang = ruang;
       this.mahasiswa = mahasiswa;
       this.matakuliah = matakuliah;
       this.jam = jam;
       this.hari = hari;
       this.absen1 = absen1;
       this.absen2 = absen2;
       this.absen3 = absen3;
       this.absen4 = absen4;
       this.absen5 = absen5;
       this.absen6 = absen6;
       this.absen7 = absen7;
       this.absen8 = absen8;
       this.absen9 = absen9;
       this.absen10 = absen10;
       this.absen11 = absen11;
       this.absen12 = absen12;
       this.absen13 = absen13;
       this.absen14 = absen14;
    }
   
    public AbsenId getId() {
        return this.id;
    }
    
    public void setId(AbsenId id) {
        this.id = id;
    }
    public Ruang getRuang() {
        return this.ruang;
    }
    
    public void setRuang(Ruang ruang) {
        this.ruang = ruang;
    }
    public Mahasiswa getMahasiswa() {
        return this.mahasiswa;
    }
    
    public void setMahasiswa(Mahasiswa mahasiswa) {
        this.mahasiswa = mahasiswa;
    }
    public Matakuliah getMatakuliah() {
        return this.matakuliah;
    }
    
    public void setMatakuliah(Matakuliah matakuliah) {
        this.matakuliah = matakuliah;
    }
    public int getJam() {
        return this.jam;
    }
    
    public void setJam(int jam) {
        this.jam = jam;
    }
    public int getHari() {
        return this.hari;
    }
    
    public void setHari(int hari) {
        this.hari = hari;
    }
    public Integer getAbsen1() {
        return this.absen1;
    }
    
    public void setAbsen1(Integer absen1) {
        this.absen1 = absen1;
    }
    public Integer getAbsen2() {
        return this.absen2;
    }
    
    public void setAbsen2(Integer absen2) {
        this.absen2 = absen2;
    }
    public Integer getAbsen3() {
        return this.absen3;
    }
    
    public void setAbsen3(Integer absen3) {
        this.absen3 = absen3;
    }
    public Integer getAbsen4() {
        return this.absen4;
    }
    
    public void setAbsen4(Integer absen4) {
        this.absen4 = absen4;
    }
    public Integer getAbsen5() {
        return this.absen5;
    }
    
    public void setAbsen5(Integer absen5) {
        this.absen5 = absen5;
    }
    public Integer getAbsen6() {
        return this.absen6;
    }
    
    public void setAbsen6(Integer absen6) {
        this.absen6 = absen6;
    }
    public Integer getAbsen7() {
        return this.absen7;
    }
    
    public void setAbsen7(Integer absen7) {
        this.absen7 = absen7;
    }
    public Integer getAbsen8() {
        return this.absen8;
    }
    
    public void setAbsen8(Integer absen8) {
        this.absen8 = absen8;
    }
    public Integer getAbsen9() {
        return this.absen9;
    }
    
    public void setAbsen9(Integer absen9) {
        this.absen9 = absen9;
    }
    public Integer getAbsen10() {
        return this.absen10;
    }
    
    public void setAbsen10(Integer absen10) {
        this.absen10 = absen10;
    }
    public Integer getAbsen11() {
        return this.absen11;
    }
    
    public void setAbsen11(Integer absen11) {
        this.absen11 = absen11;
    }
    public Integer getAbsen12() {
        return this.absen12;
    }
    
    public void setAbsen12(Integer absen12) {
        this.absen12 = absen12;
    }
    public Integer getAbsen13() {
        return this.absen13;
    }
    
    public void setAbsen13(Integer absen13) {
        this.absen13 = absen13;
    }
    public Integer getAbsen14() {
        return this.absen14;
    }
    
    public void setAbsen14(Integer absen14) {
        this.absen14 = absen14;
    }




}


