package com.sia.model;
// Generated Apr 8, 2013 1:51:16 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Ambil generated by hbm2java
 */
public class Ambil  implements java.io.Serializable {


     private AmbilId id;
     private Mahasiswa mahasiswa;
     private Matakuliah matakuliah;
     private Date tglAmbil;
     private int semesterKe;

    public Ambil() {
    }

    public Ambil(AmbilId id, Mahasiswa mahasiswa, Matakuliah matakuliah, Date tglAmbil, int semesterKe) {
       this.id = id;
       this.mahasiswa = mahasiswa;
       this.matakuliah = matakuliah;
       this.tglAmbil = tglAmbil;
       this.semesterKe = semesterKe;
    }
   
    public AmbilId getId() {
        return this.id;
    }
    
    public void setId(AmbilId id) {
        this.id = id;
    }
    public Mahasiswa getMahasiswa() {
        return this.mahasiswa;
    }
    
    public void setMahasiswa(Mahasiswa mahasiswa) {
        this.mahasiswa = mahasiswa;
    }
    public Matakuliah getMatakuliah() {
        return this.matakuliah;
    }
    
    public void setMatakuliah(Matakuliah matakuliah) {
        this.matakuliah = matakuliah;
    }
    public Date getTglAmbil() {
        return this.tglAmbil;
    }
    
    public void setTglAmbil(Date tglAmbil) {
        this.tglAmbil = tglAmbil;
    }
    public int getSemesterKe() {
        return this.semesterKe;
    }
    
    public void setSemesterKe(int semesterKe) {
        this.semesterKe = semesterKe;
    }




}


