package com.sia.model;
// Generated Apr 8, 2013 1:51:16 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Atur generated by hbm2java
 */
public class Atur  implements java.io.Serializable {


     private AturId id;
     private Dosen dosen;
     private Ruang ruang;
     private Matakuliah matakuliah;
     private Date jam;
     private Date hari;

    public Atur() {
    }

	
    public Atur(AturId id, Dosen dosen, Matakuliah matakuliah, Date jam, Date hari) {
        this.id = id;
        this.dosen = dosen;
        this.matakuliah = matakuliah;
        this.jam = jam;
        this.hari = hari;
    }
    public Atur(AturId id, Dosen dosen, Ruang ruang, Matakuliah matakuliah, Date jam, Date hari) {
       this.id = id;
       this.dosen = dosen;
       this.ruang = ruang;
       this.matakuliah = matakuliah;
       this.jam = jam;
       this.hari = hari;
    }
   
    public AturId getId() {
        return this.id;
    }
    
    public void setId(AturId id) {
        this.id = id;
    }
    public Dosen getDosen() {
        return this.dosen;
    }
    
    public void setDosen(Dosen dosen) {
        this.dosen = dosen;
    }
    public Ruang getRuang() {
        return this.ruang;
    }
    
    public void setRuang(Ruang ruang) {
        this.ruang = ruang;
    }
    public Matakuliah getMatakuliah() {
        return this.matakuliah;
    }
    
    public void setMatakuliah(Matakuliah matakuliah) {
        this.matakuliah = matakuliah;
    }
    public Date getJam() {
        return this.jam;
    }
    
    public void setJam(Date jam) {
        this.jam = jam;
    }
    public Date getHari() {
        return this.hari;
    }
    
    public void setHari(Date hari) {
        this.hari = hari;
    }




}


