package com.sia.model;
// Generated Apr 8, 2013 1:51:16 PM by Hibernate Tools 3.2.1.GA



/**
 * AturId generated by hbm2java
 */
public class AturId  implements java.io.Serializable {


     private int kodeMk;
     private int kodeRuang;
     private int nik;

    public AturId() {
    }

    public AturId(int kodeMk, int kodeRuang, int nik) {
       this.kodeMk = kodeMk;
       this.kodeRuang = kodeRuang;
       this.nik = nik;
    }
   
    public int getKodeMk() {
        return this.kodeMk;
    }
    
    public void setKodeMk(int kodeMk) {
        this.kodeMk = kodeMk;
    }
    public int getKodeRuang() {
        return this.kodeRuang;
    }
    
    public void setKodeRuang(int kodeRuang) {
        this.kodeRuang = kodeRuang;
    }
    public int getNik() {
        return this.nik;
    }
    
    public void setNik(int nik) {
        this.nik = nik;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AturId) ) return false;
		 AturId castOther = ( AturId ) other; 
         
		 return (this.getKodeMk()==castOther.getKodeMk())
 && (this.getKodeRuang()==castOther.getKodeRuang())
 && (this.getNik()==castOther.getNik());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getKodeMk();
         result = 37 * result + this.getKodeRuang();
         result = 37 * result + this.getNik();
         return result;
   }   


}


