package com.sia.model;
// Generated Apr 8, 2013 1:51:16 PM by Hibernate Tools 3.2.1.GA



/**
 * BiayaId generated by hbm2java
 */
public class BiayaId  implements java.io.Serializable {


     private int kodeProd;
     private int angkatan;

    public BiayaId() {
    }

    public BiayaId(int kodeProd, int angkatan) {
       this.kodeProd = kodeProd;
       this.angkatan = angkatan;
    }
   
    public int getKodeProd() {
        return this.kodeProd;
    }
    
    public void setKodeProd(int kodeProd) {
        this.kodeProd = kodeProd;
    }
    public int getAngkatan() {
        return this.angkatan;
    }
    
    public void setAngkatan(int angkatan) {
        this.angkatan = angkatan;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BiayaId) ) return false;
		 BiayaId castOther = ( BiayaId ) other; 
         
		 return (this.getKodeProd()==castOther.getKodeProd())
 && (this.getAngkatan()==castOther.getAngkatan());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getKodeProd();
         result = 37 * result + this.getAngkatan();
         return result;
   }   


}


