package com.sia.model;
// Generated Apr 8, 2013 1:51:16 PM by Hibernate Tools 3.2.1.GA



/**
 * BiayakhususId generated by hbm2java
 */
public class BiayakhususId  implements java.io.Serializable {


     private int kodeProd;
     private int angkatan;
     private int kode;

    public BiayakhususId() {
    }

    public BiayakhususId(int kodeProd, int angkatan, int kode) {
       this.kodeProd = kodeProd;
       this.angkatan = angkatan;
       this.kode = kode;
    }
   
    public int getKodeProd() {
        return this.kodeProd;
    }
    
    public void setKodeProd(int kodeProd) {
        this.kodeProd = kodeProd;
    }
    public int getAngkatan() {
        return this.angkatan;
    }
    
    public void setAngkatan(int angkatan) {
        this.angkatan = angkatan;
    }
    public int getKode() {
        return this.kode;
    }
    
    public void setKode(int kode) {
        this.kode = kode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BiayakhususId) ) return false;
		 BiayakhususId castOther = ( BiayakhususId ) other; 
         
		 return (this.getKodeProd()==castOther.getKodeProd())
 && (this.getAngkatan()==castOther.getAngkatan())
 && (this.getKode()==castOther.getKode());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getKodeProd();
         result = 37 * result + this.getAngkatan();
         result = 37 * result + this.getKode();
         return result;
   }   


}


