package com.sia.model;
// Generated Apr 8, 2013 1:51:16 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Dosen generated by hbm2java
 */
public class Dosen  implements java.io.Serializable {


     private int nik;
     private Dosen dosen;
     private String nama;
     private String password;
     private Set prodis = new HashSet(0);
     private Set aturs = new HashSet(0);
     private Set mengajars = new HashSet(0);
     private Set mahasiswas = new HashSet(0);
     private Set dosens = new HashSet(0);

    public Dosen() {
    }

	
    public Dosen(int nik) {
        this.nik = nik;
    }
    public Dosen(int nik, Dosen dosen, String nama, String password, Set prodis, Set aturs, Set mengajars, Set mahasiswas, Set dosens) {
       this.nik = nik;
       this.dosen = dosen;
       this.nama = nama;
       this.password = password;
       this.prodis = prodis;
       this.aturs = aturs;
       this.mengajars = mengajars;
       this.mahasiswas = mahasiswas;
       this.dosens = dosens;
    }
   
    public int getNik() {
        return this.nik;
    }
    
    public void setNik(int nik) {
        this.nik = nik;
    }
    public Dosen getDosen() {
        return this.dosen;
    }
    
    public void setDosen(Dosen dosen) {
        this.dosen = dosen;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getProdis() {
        return this.prodis;
    }
    
    public void setProdis(Set prodis) {
        this.prodis = prodis;
    }
    public Set getAturs() {
        return this.aturs;
    }
    
    public void setAturs(Set aturs) {
        this.aturs = aturs;
    }
    public Set getMengajars() {
        return this.mengajars;
    }
    
    public void setMengajars(Set mengajars) {
        this.mengajars = mengajars;
    }
    public Set getMahasiswas() {
        return this.mahasiswas;
    }
    
    public void setMahasiswas(Set mahasiswas) {
        this.mahasiswas = mahasiswas;
    }
    public Set getDosens() {
        return this.dosens;
    }
    
    public void setDosens(Set dosens) {
        this.dosens = dosens;
    }




}


