package com.sia.model;
// Generated Apr 8, 2013 1:51:16 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Fakultas generated by hbm2java
 */
public class Fakultas  implements java.io.Serializable {


     private int kodeFak;
     private String namaFak;
     private Set prodis = new HashSet(0);

    public Fakultas() {
    }

	
    public Fakultas(int kodeFak) {
        this.kodeFak = kodeFak;
    }
    public Fakultas(int kodeFak, String namaFak, Set prodis) {
       this.kodeFak = kodeFak;
       this.namaFak = namaFak;
       this.prodis = prodis;
    }
   
    public int getKodeFak() {
        return this.kodeFak;
    }
    
    public void setKodeFak(int kodeFak) {
        this.kodeFak = kodeFak;
    }
    public String getNamaFak() {
        return this.namaFak;
    }
    
    public void setNamaFak(String namaFak) {
        this.namaFak = namaFak;
    }
    public Set getProdis() {
        return this.prodis;
    }
    
    public void setProdis(Set prodis) {
        this.prodis = prodis;
    }




}


