package com.sia.model;
// Generated Apr 8, 2013 1:51:16 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Hakakses generated by hbm2java
 */
public class Hakakses  implements java.io.Serializable {


     private int no;
     private String pengguna;
     private Integer badanHukum_PerguruanTinggiView;
     private Integer badanHukum_PerguruanTinggiEdit;
     private Integer fakDeptProdiView;
     private Integer fakDeptProdiEdit;
     private Integer dosenView;
     private Integer dosenEdit;
     private Integer mahasiswaAlumniView;
     private Integer mahasiswaAlumniEdit;
     private Integer matkulKurikulumView;
     private Integer matkulKurikulumEdit;
     private Integer keuanganView;
     private Integer keuanganEdit;
     private Integer tataUsahaView;
     private Integer tataUsahaEdit;
     private Set mahasiswas = new HashSet(0);

    public Hakakses() {
    }

	
    public Hakakses(int no) {
        this.no = no;
    }
    public Hakakses(int no, String pengguna, Integer badanHukum_PerguruanTinggiView, Integer badanHukum_PerguruanTinggiEdit, Integer fakDeptProdiView, Integer fakDeptProdiEdit, Integer dosenView, Integer dosenEdit, Integer mahasiswaAlumniView, Integer mahasiswaAlumniEdit, Integer matkulKurikulumView, Integer matkulKurikulumEdit, Integer keuanganView, Integer keuanganEdit, Integer tataUsahaView, Integer tataUsahaEdit, Set mahasiswas) {
       this.no = no;
       this.pengguna = pengguna;
       this.badanHukum_PerguruanTinggiView = badanHukum_PerguruanTinggiView;
       this.badanHukum_PerguruanTinggiEdit = badanHukum_PerguruanTinggiEdit;
       this.fakDeptProdiView = fakDeptProdiView;
       this.fakDeptProdiEdit = fakDeptProdiEdit;
       this.dosenView = dosenView;
       this.dosenEdit = dosenEdit;
       this.mahasiswaAlumniView = mahasiswaAlumniView;
       this.mahasiswaAlumniEdit = mahasiswaAlumniEdit;
       this.matkulKurikulumView = matkulKurikulumView;
       this.matkulKurikulumEdit = matkulKurikulumEdit;
       this.keuanganView = keuanganView;
       this.keuanganEdit = keuanganEdit;
       this.tataUsahaView = tataUsahaView;
       this.tataUsahaEdit = tataUsahaEdit;
       this.mahasiswas = mahasiswas;
    }
   
    public int getNo() {
        return this.no;
    }
    
    public void setNo(int no) {
        this.no = no;
    }
    public String getPengguna() {
        return this.pengguna;
    }
    
    public void setPengguna(String pengguna) {
        this.pengguna = pengguna;
    }
    public Integer getBadanHukum_PerguruanTinggiView() {
        return this.badanHukum_PerguruanTinggiView;
    }
    
    public void setBadanHukum_PerguruanTinggiView(Integer badanHukum_PerguruanTinggiView) {
        this.badanHukum_PerguruanTinggiView = badanHukum_PerguruanTinggiView;
    }
    public Integer getBadanHukum_PerguruanTinggiEdit() {
        return this.badanHukum_PerguruanTinggiEdit;
    }
    
    public void setBadanHukum_PerguruanTinggiEdit(Integer badanHukum_PerguruanTinggiEdit) {
        this.badanHukum_PerguruanTinggiEdit = badanHukum_PerguruanTinggiEdit;
    }
    public Integer getFakDeptProdiView() {
        return this.fakDeptProdiView;
    }
    
    public void setFakDeptProdiView(Integer fakDeptProdiView) {
        this.fakDeptProdiView = fakDeptProdiView;
    }
    public Integer getFakDeptProdiEdit() {
        return this.fakDeptProdiEdit;
    }
    
    public void setFakDeptProdiEdit(Integer fakDeptProdiEdit) {
        this.fakDeptProdiEdit = fakDeptProdiEdit;
    }
    public Integer getDosenView() {
        return this.dosenView;
    }
    
    public void setDosenView(Integer dosenView) {
        this.dosenView = dosenView;
    }
    public Integer getDosenEdit() {
        return this.dosenEdit;
    }
    
    public void setDosenEdit(Integer dosenEdit) {
        this.dosenEdit = dosenEdit;
    }
    public Integer getMahasiswaAlumniView() {
        return this.mahasiswaAlumniView;
    }
    
    public void setMahasiswaAlumniView(Integer mahasiswaAlumniView) {
        this.mahasiswaAlumniView = mahasiswaAlumniView;
    }
    public Integer getMahasiswaAlumniEdit() {
        return this.mahasiswaAlumniEdit;
    }
    
    public void setMahasiswaAlumniEdit(Integer mahasiswaAlumniEdit) {
        this.mahasiswaAlumniEdit = mahasiswaAlumniEdit;
    }
    public Integer getMatkulKurikulumView() {
        return this.matkulKurikulumView;
    }
    
    public void setMatkulKurikulumView(Integer matkulKurikulumView) {
        this.matkulKurikulumView = matkulKurikulumView;
    }
    public Integer getMatkulKurikulumEdit() {
        return this.matkulKurikulumEdit;
    }
    
    public void setMatkulKurikulumEdit(Integer matkulKurikulumEdit) {
        this.matkulKurikulumEdit = matkulKurikulumEdit;
    }
    public Integer getKeuanganView() {
        return this.keuanganView;
    }
    
    public void setKeuanganView(Integer keuanganView) {
        this.keuanganView = keuanganView;
    }
    public Integer getKeuanganEdit() {
        return this.keuanganEdit;
    }
    
    public void setKeuanganEdit(Integer keuanganEdit) {
        this.keuanganEdit = keuanganEdit;
    }
    public Integer getTataUsahaView() {
        return this.tataUsahaView;
    }
    
    public void setTataUsahaView(Integer tataUsahaView) {
        this.tataUsahaView = tataUsahaView;
    }
    public Integer getTataUsahaEdit() {
        return this.tataUsahaEdit;
    }
    
    public void setTataUsahaEdit(Integer tataUsahaEdit) {
        this.tataUsahaEdit = tataUsahaEdit;
    }
    public Set getMahasiswas() {
        return this.mahasiswas;
    }
    
    public void setMahasiswas(Set mahasiswas) {
        this.mahasiswas = mahasiswas;
    }




}


