package com.sia.model;
// Generated Apr 8, 2013 1:51:16 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Mahasiswa generated by hbm2java
 */
public class Mahasiswa  implements java.io.Serializable {


     private int nim;
     private Staff staff;
     private Prodi prodi;
     private Dosen dosen;
     private String namaMhs;
     private Date tglLahir;
     private String alamat;
     private Double ips;
     private Double ipk;
     private Integer statusLulus;
     private Set nilais = new HashSet(0);
     private Set hakakseses = new HashSet(0);
     private Set absens = new HashSet(0);
     private Set ambils = new HashSet(0);

    public Mahasiswa() {
    }

	
    public Mahasiswa(int nim, Prodi prodi, Dosen dosen) {
        this.nim = nim;
        this.prodi = prodi;
        this.dosen = dosen;
    }
    public Mahasiswa(int nim, Staff staff, Prodi prodi, Dosen dosen, String namaMhs, Date tglLahir, String alamat, Double ips, Double ipk, Integer statusLulus, Set nilais, Set hakakseses, Set absens, Set ambils) {
       this.nim = nim;
       this.staff = staff;
       this.prodi = prodi;
       this.dosen = dosen;
       this.namaMhs = namaMhs;
       this.tglLahir = tglLahir;
       this.alamat = alamat;
       this.ips = ips;
       this.ipk = ipk;
       this.statusLulus = statusLulus;
       this.nilais = nilais;
       this.hakakseses = hakakseses;
       this.absens = absens;
       this.ambils = ambils;
    }
   
    public int getNim() {
        return this.nim;
    }
    
    public void setNim(int nim) {
        this.nim = nim;
    }
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }
    public Prodi getProdi() {
        return this.prodi;
    }
    
    public void setProdi(Prodi prodi) {
        this.prodi = prodi;
    }
    public Dosen getDosen() {
        return this.dosen;
    }
    
    public void setDosen(Dosen dosen) {
        this.dosen = dosen;
    }
    public String getNamaMhs() {
        return this.namaMhs;
    }
    
    public void setNamaMhs(String namaMhs) {
        this.namaMhs = namaMhs;
    }
    public Date getTglLahir() {
        return this.tglLahir;
    }
    
    public void setTglLahir(Date tglLahir) {
        this.tglLahir = tglLahir;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public Double getIps() {
        return this.ips;
    }
    
    public void setIps(Double ips) {
        this.ips = ips;
    }
    public Double getIpk() {
        return this.ipk;
    }
    
    public void setIpk(Double ipk) {
        this.ipk = ipk;
    }
    public Integer getStatusLulus() {
        return this.statusLulus;
    }
    
    public void setStatusLulus(Integer statusLulus) {
        this.statusLulus = statusLulus;
    }
    public Set getNilais() {
        return this.nilais;
    }
    
    public void setNilais(Set nilais) {
        this.nilais = nilais;
    }
    public Set getHakakseses() {
        return this.hakakseses;
    }
    
    public void setHakakseses(Set hakakseses) {
        this.hakakseses = hakakseses;
    }
    public Set getAbsens() {
        return this.absens;
    }
    
    public void setAbsens(Set absens) {
        this.absens = absens;
    }
    public Set getAmbils() {
        return this.ambils;
    }
    
    public void setAmbils(Set ambils) {
        this.ambils = ambils;
    }




}


