package com.sia.model;
// Generated Apr 8, 2013 1:51:16 PM by Hibernate Tools 3.2.1.GA



/**
 * MengajarId generated by hbm2java
 */
public class MengajarId  implements java.io.Serializable {


     private int nik;
     private int kodeMk;
     private int kodeRuang;

    public MengajarId() {
    }

    public MengajarId(int nik, int kodeMk, int kodeRuang) {
       this.nik = nik;
       this.kodeMk = kodeMk;
       this.kodeRuang = kodeRuang;
    }
   
    public int getNik() {
        return this.nik;
    }
    
    public void setNik(int nik) {
        this.nik = nik;
    }
    public int getKodeMk() {
        return this.kodeMk;
    }
    
    public void setKodeMk(int kodeMk) {
        this.kodeMk = kodeMk;
    }
    public int getKodeRuang() {
        return this.kodeRuang;
    }
    
    public void setKodeRuang(int kodeRuang) {
        this.kodeRuang = kodeRuang;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MengajarId) ) return false;
		 MengajarId castOther = ( MengajarId ) other; 
         
		 return (this.getNik()==castOther.getNik())
 && (this.getKodeMk()==castOther.getKodeMk())
 && (this.getKodeRuang()==castOther.getKodeRuang());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNik();
         result = 37 * result + this.getKodeMk();
         result = 37 * result + this.getKodeRuang();
         return result;
   }   


}


