package com.sia.model;
// Generated Apr 8, 2013 1:51:16 PM by Hibernate Tools 3.2.1.GA



/**
 * Nilai generated by hbm2java
 */
public class Nilai  implements java.io.Serializable {


     private NilaiId id;
     private Mahasiswa mahasiswa;
     private Matakuliah matakuliah;
     private Integer nilai1;
     private Integer nilai2;
     private Integer nilai3;
     private Integer nilai4;
     private Integer nilai5;

    public Nilai() {
    }

	
    public Nilai(NilaiId id, Mahasiswa mahasiswa, Matakuliah matakuliah) {
        this.id = id;
        this.mahasiswa = mahasiswa;
        this.matakuliah = matakuliah;
    }
    public Nilai(NilaiId id, Mahasiswa mahasiswa, Matakuliah matakuliah, Integer nilai1, Integer nilai2, Integer nilai3, Integer nilai4, Integer nilai5) {
       this.id = id;
       this.mahasiswa = mahasiswa;
       this.matakuliah = matakuliah;
       this.nilai1 = nilai1;
       this.nilai2 = nilai2;
       this.nilai3 = nilai3;
       this.nilai4 = nilai4;
       this.nilai5 = nilai5;
    }
   
    public NilaiId getId() {
        return this.id;
    }
    
    public void setId(NilaiId id) {
        this.id = id;
    }
    public Mahasiswa getMahasiswa() {
        return this.mahasiswa;
    }
    
    public void setMahasiswa(Mahasiswa mahasiswa) {
        this.mahasiswa = mahasiswa;
    }
    public Matakuliah getMatakuliah() {
        return this.matakuliah;
    }
    
    public void setMatakuliah(Matakuliah matakuliah) {
        this.matakuliah = matakuliah;
    }
    public Integer getNilai1() {
        return this.nilai1;
    }
    
    public void setNilai1(Integer nilai1) {
        this.nilai1 = nilai1;
    }
    public Integer getNilai2() {
        return this.nilai2;
    }
    
    public void setNilai2(Integer nilai2) {
        this.nilai2 = nilai2;
    }
    public Integer getNilai3() {
        return this.nilai3;
    }
    
    public void setNilai3(Integer nilai3) {
        this.nilai3 = nilai3;
    }
    public Integer getNilai4() {
        return this.nilai4;
    }
    
    public void setNilai4(Integer nilai4) {
        this.nilai4 = nilai4;
    }
    public Integer getNilai5() {
        return this.nilai5;
    }
    
    public void setNilai5(Integer nilai5) {
        this.nilai5 = nilai5;
    }




}


