package com.sia.model;
// Generated Apr 8, 2013 1:51:16 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Prodi generated by hbm2java
 */
public class Prodi  implements java.io.Serializable {


     private int kodeProd;
     private Fakultas fakultas;
     private String namaProd;
     private Set biayas = new HashSet(0);
     private Set biayakhususes = new HashSet(0);
     private Set mahasiswas = new HashSet(0);
     private Set dosens = new HashSet(0);

    public Prodi() {
    }

	
    public Prodi(int kodeProd, Fakultas fakultas) {
        this.kodeProd = kodeProd;
        this.fakultas = fakultas;
    }
    public Prodi(int kodeProd, Fakultas fakultas, String namaProd, Set biayas, Set biayakhususes, Set mahasiswas, Set dosens) {
       this.kodeProd = kodeProd;
       this.fakultas = fakultas;
       this.namaProd = namaProd;
       this.biayas = biayas;
       this.biayakhususes = biayakhususes;
       this.mahasiswas = mahasiswas;
       this.dosens = dosens;
    }
   
    public int getKodeProd() {
        return this.kodeProd;
    }
    
    public void setKodeProd(int kodeProd) {
        this.kodeProd = kodeProd;
    }
    public Fakultas getFakultas() {
        return this.fakultas;
    }
    
    public void setFakultas(Fakultas fakultas) {
        this.fakultas = fakultas;
    }
    public String getNamaProd() {
        return this.namaProd;
    }
    
    public void setNamaProd(String namaProd) {
        this.namaProd = namaProd;
    }
    public Set getBiayas() {
        return this.biayas;
    }
    
    public void setBiayas(Set biayas) {
        this.biayas = biayas;
    }
    public Set getBiayakhususes() {
        return this.biayakhususes;
    }
    
    public void setBiayakhususes(Set biayakhususes) {
        this.biayakhususes = biayakhususes;
    }
    public Set getMahasiswas() {
        return this.mahasiswas;
    }
    
    public void setMahasiswas(Set mahasiswas) {
        this.mahasiswas = mahasiswas;
    }
    public Set getDosens() {
        return this.dosens;
    }
    
    public void setDosens(Set dosens) {
        this.dosens = dosens;
    }




}


