package com.sia.model;
// Generated Apr 8, 2013 1:51:16 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Ruang generated by hbm2java
 */
public class Ruang  implements java.io.Serializable {


     private int kodeRuang;
     private Matakuliah matakuliah;
     private String namaRuang;
     private Set aturs = new HashSet(0);
     private Set absens = new HashSet(0);
     private Set waktus = new HashSet(0);
     private Set mengajars = new HashSet(0);

    public Ruang() {
    }

	
    public Ruang(int kodeRuang) {
        this.kodeRuang = kodeRuang;
    }
    public Ruang(int kodeRuang, Matakuliah matakuliah, String namaRuang, Set aturs, Set absens, Set waktus, Set mengajars) {
       this.kodeRuang = kodeRuang;
       this.matakuliah = matakuliah;
       this.namaRuang = namaRuang;
       this.aturs = aturs;
       this.absens = absens;
       this.waktus = waktus;
       this.mengajars = mengajars;
    }
   
    public int getKodeRuang() {
        return this.kodeRuang;
    }
    
    public void setKodeRuang(int kodeRuang) {
        this.kodeRuang = kodeRuang;
    }
    public Matakuliah getMatakuliah() {
        return this.matakuliah;
    }
    
    public void setMatakuliah(Matakuliah matakuliah) {
        this.matakuliah = matakuliah;
    }
    public String getNamaRuang() {
        return this.namaRuang;
    }
    
    public void setNamaRuang(String namaRuang) {
        this.namaRuang = namaRuang;
    }
    public Set getAturs() {
        return this.aturs;
    }
    
    public void setAturs(Set aturs) {
        this.aturs = aturs;
    }
    public Set getAbsens() {
        return this.absens;
    }
    
    public void setAbsens(Set absens) {
        this.absens = absens;
    }
    public Set getWaktus() {
        return this.waktus;
    }
    
    public void setWaktus(Set waktus) {
        this.waktus = waktus;
    }
    public Set getMengajars() {
        return this.mengajars;
    }
    
    public void setMengajars(Set mengajars) {
        this.mengajars = mengajars;
    }




}


