package com.sia.model;
// Generated Apr 8, 2013 1:51:16 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Waktu generated by hbm2java
 */
public class Waktu  implements java.io.Serializable {


     private WaktuId id;
     private Ruang ruang;
     private Matakuliah matakuliah;
     private Integer jam;
     private Date hari;

    public Waktu() {
    }

	
    public Waktu(WaktuId id, Ruang ruang, Matakuliah matakuliah) {
        this.id = id;
        this.ruang = ruang;
        this.matakuliah = matakuliah;
    }
    public Waktu(WaktuId id, Ruang ruang, Matakuliah matakuliah, Integer jam, Date hari) {
       this.id = id;
       this.ruang = ruang;
       this.matakuliah = matakuliah;
       this.jam = jam;
       this.hari = hari;
    }
   
    public WaktuId getId() {
        return this.id;
    }
    
    public void setId(WaktuId id) {
        this.id = id;
    }
    public Ruang getRuang() {
        return this.ruang;
    }
    
    public void setRuang(Ruang ruang) {
        this.ruang = ruang;
    }
    public Matakuliah getMatakuliah() {
        return this.matakuliah;
    }
    
    public void setMatakuliah(Matakuliah matakuliah) {
        this.matakuliah = matakuliah;
    }
    public Integer getJam() {
        return this.jam;
    }
    
    public void setJam(Integer jam) {
        this.jam = jam;
    }
    public Date getHari() {
        return this.hari;
    }
    
    public void setHari(Date hari) {
        this.hari = hari;
    }




}


