package com.sia.model;
// Generated Apr 8, 2013 1:51:16 PM by Hibernate Tools 3.2.1.GA



/**
 * WaktuId generated by hbm2java
 */
public class WaktuId  implements java.io.Serializable {


     private int kodeMk;
     private int kodeRuang;
     private String kelas;

    public WaktuId() {
    }

    public WaktuId(int kodeMk, int kodeRuang, String kelas) {
       this.kodeMk = kodeMk;
       this.kodeRuang = kodeRuang;
       this.kelas = kelas;
    }
   
    public int getKodeMk() {
        return this.kodeMk;
    }
    
    public void setKodeMk(int kodeMk) {
        this.kodeMk = kodeMk;
    }
    public int getKodeRuang() {
        return this.kodeRuang;
    }
    
    public void setKodeRuang(int kodeRuang) {
        this.kodeRuang = kodeRuang;
    }
    public String getKelas() {
        return this.kelas;
    }
    
    public void setKelas(String kelas) {
        this.kelas = kelas;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof WaktuId) ) return false;
		 WaktuId castOther = ( WaktuId ) other; 
         
		 return (this.getKodeMk()==castOther.getKodeMk())
 && (this.getKodeRuang()==castOther.getKodeRuang())
 && ( (this.getKelas()==castOther.getKelas()) || ( this.getKelas()!=null && castOther.getKelas()!=null && this.getKelas().equals(castOther.getKelas()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getKodeMk();
         result = 37 * result + this.getKodeRuang();
         result = 37 * result + ( getKelas() == null ? 0 : this.getKelas().hashCode() );
         return result;
   }   


}


